name: Java CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Deploy to heroku using an action
        uses: akhileshns/heroku-deploy@v3.2.6
        with:
          appdir: Backend/ds_assignment/
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "movie-reservasion-backend" 
          heroku_email: "researchprojectsliit@gmail.com"
